### ISSUE TITLE
JSDOM vs JSDOC confusion

### ISSUE THREAD

**Issue by rub1e** [dwyl/todomvc-vanilla-javascript-example#6]
Minor point, but the first appearance of `JSDOC` threw me a bit as it hadn't been referred to before and I just read it as `JSDOM`

Suggest changing "Testing" heading to "Testing & Documentation" and adding a line saying "We will use JSDOC for documentation" with a link to https://github.com/dwyl/learn-jsdoc

Let me know what you think and I'll do a PR if you think this is a useful clarification

**Comment by nelsonic** [comment]
@rub1e great points; thanks for taking a look at this with a fresh pair of eyes. 🙌
If you have time to PR an update would be great to clarify JSDOC vs. JSDOM and link to the other repo for more detail. 👍🏻

**Comment by rub1e** [comment]
Yeah I was just zipping through it while avoiding my own work - I'll go through it properly when I have the chance - keen to learn `TEA`!

PR: https://github.com/dwyl/todomvc-vanilla-javascript-elm-architecture-example/pull/7

**Comment by nelsonic** [comment]
@rub1e thanks for the PR clarifying JSDOC vs JSDOM. 🎉 
Our hope is that this tutorial will show complete beginners 🌱 & TDD-doubers in the JS community 🌍
that TDD is not only viable, it's _easy_ and efficient once you you get a bit of an intro and practice. 🚀 
Look forward to hearing your feedback when you get a chance to go through the full example. 💬
